# ============ COLOR PALETTE ============
# All FOREGROUND and BACKGROUND color values (xterm-256 indices 0-255).
# To preview the palette:
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# ---- BACKGROUNDS ----

typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent

# ---- FOREGROUNDS ----

# -- Layout --
typeset -g POWERLEVEL9K_RULER_FOREGROUND=242

# -- OS icon --
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=

# -- Prompt char --
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196

# -- Directory --
typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=66

# -- VCS (git) --
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=76
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=244
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=76
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178

# -- Status --
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=76
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=76
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=196

# -- Command execution time --
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=178

# -- Background jobs --
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70

# -- Direnv --
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=178

# -- asdf --
typeset -g POWERLEVEL9K_ASDF_FOREGROUND=66
typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND=168
typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=37
typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=37
typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=70
typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND=37
typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=134
typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=38
typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND=32
typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND=32
typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND=67
typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=125
typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=129
typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=31
typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND=99
typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=172
typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND=70

# -- Shell indicators --
typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=39
typeset -g POWERLEVEL9K_RANGER_FOREGROUND=178
typeset -g POWERLEVEL9K_YAZI_FOREGROUND=178
typeset -g POWERLEVEL9K_NNN_FOREGROUND=72
typeset -g POWERLEVEL9K_LF_FOREGROUND=72
typeset -g POWERLEVEL9K_XPLR_FOREGROUND=72
typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND=34
typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND=178
typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=74
typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=33

# -- System resources --
typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=35
typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=220
typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=160
typeset -g POWERLEVEL9K_RAM_FOREGROUND=66
typeset -g POWERLEVEL9K_SWAP_FOREGROUND=96
typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=66
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=178
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=166

# -- Task managers --
typeset -g POWERLEVEL9K_TODO_FOREGROUND=110
typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=110
typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=74

# -- Per-directory history --
typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=135
typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=130

# -- CPU arch --
typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=172

# -- Context (user@host) --
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=178
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=180
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=180

# -- Language version managers --
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=37
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=37
typeset -g POWERLEVEL9K_GOENV_FOREGROUND=37
typeset -g POWERLEVEL9K_NODENV_FOREGROUND=70
typeset -g POWERLEVEL9K_NVM_FOREGROUND=70
typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=70
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=37
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=37
typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=134
typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=99
typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=161
typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=32
typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=117
typeset -g POWERLEVEL9K_RBENV_FOREGROUND=168
typeset -g POWERLEVEL9K_RVM_FOREGROUND=168
typeset -g POWERLEVEL9K_FVM_FOREGROUND=38
typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=32
typeset -g POWERLEVEL9K_JENV_FOREGROUND=32
typeset -g POWERLEVEL9K_PLENV_FOREGROUND=67
typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND=67
typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=99
typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=160
typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=172

# -- Cloud / DevOps --
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=134
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=38
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=38
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=208
typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=70
typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=32
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=32
typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=32

# -- Network / misc --
typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=178
typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=94
typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=81
typeset -g POWERLEVEL9K_IP_FOREGROUND=38
typeset -g POWERLEVEL9K_PROXY_FOREGROUND=68
typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=160
typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=70
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=178
typeset -g POWERLEVEL9K_WIFI_FOREGROUND=68
typeset -g POWERLEVEL9K_TIME_FOREGROUND=66

# ---- ACCENTS ----
# Inline git-status colors — local vars inside my_git_formatter() in segments.zsh:
#   clean      %76F   (green)   matches VCS_CLEAN_FOREGROUND above
#   modified   %178F  (yellow)  matches VCS_MODIFIED_FOREGROUND above
#   untracked  %39F   (blue)
#   conflicted %196F  (red)
#   stale      %244F  (grey, all states when loading)

# ============ WezTerm colors ============
# When switching WezTerm color schemes, update these key prompt colors to match:
#
#   Prompt role           | Variable                              | Value
#   ----------------------|---------------------------------------|-------
#   directory             | POWERLEVEL9K_DIR_FOREGROUND           | 31   (blue)
#   directory anchor      | POWERLEVEL9K_DIR_ANCHOR_FOREGROUND    | 39   (bright blue)
#   git clean             | POWERLEVEL9K_VCS_CLEAN_FOREGROUND     | 76   (green)
#   git modified          | POWERLEVEL9K_VCS_MODIFIED_FOREGROUND  | 178  (yellow)
#   prompt ok (❯)         | POWERLEVEL9K_PROMPT_CHAR_OK_*         | 76   (green)
#   prompt error (❯)      | POWERLEVEL9K_PROMPT_CHAR_ERROR_*      | 196  (red)
#   time                  | POWERLEVEL9K_TIME_FOREGROUND          | 66   (teal)
#   exec time             | POWERLEVEL9K_COMMAND_EXECUTION_TIME_* | 101  (olive)
#   aws profile           | POWERLEVEL9K_AWS_DEFAULT_FOREGROUND   | 208  (orange)
