# Generated by Powerlevel10k configuration wizard on 2026-05-02 at 19:25 CEST.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 37983.
# Wizard options: nerdfont-v3 + powerline, small icons, unicode, lean, 12h time, 1 line,
# sparse, many icons, concise, transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.
#
# ──────────────────────────────────────────────────────────────────────────────
# Modular p10k configuration. Edit individual modules instead of this file:
#
#   symbols.zsh  — Nerd Font icons, separators, and glyphs
#   segments.zsh — prompt element lists and per-segment behavior
#
# Color values (below) are hand-set directly in this file to match the
# Catppuccin Mocha theme used by WezTerm (terminal/wezterm/appearance.lua)
# and Ghostty (terminal/ghostty/colors.ghostty). There is no shared color
# source file — see README.md "Colors are decentralized by design".
#
# After any change:  source ~/.p10k.zsh
# To reconfigure:    p10k configure  (overwrites this file)
# ──────────────────────────────────────────────────────────────────────────────

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Resolve this file's real path so source works through the ~/.p10k.zsh symlink.
  local _cfg="${${(%):-%x}:A:h}"

  # ============ COLOR PALETTE (Catppuccin Mocha) ============
  # Hand-set, not generated. To preview the 256-color palette:
  #   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

  # ---- BACKGROUNDS ----

  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent

  # ---- FOREGROUNDS ----

  # -- Layout --
  typeset -g POWERLEVEL9K_RULER_FOREGROUND=242

  # -- OS icon --
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=

  # -- Prompt char --
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#a6e3a1'     # green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#f38ba8'  # red

  # -- Directory --
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='#89b4fa'           # blue
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#74c7ec'    # sapphire

  # -- VCS (git) --
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR='#a6e3a1'          # green
  typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=244
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#a6e3a1'                 # green
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#a6e3a1'             # green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#f9e2af'              # yellow

  # -- Status --
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#a6e3a1'            # green
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#a6e3a1'       # green
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#f38ba8'         # red
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#f38ba8'  # red
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#f38ba8'    # red

  # -- Command execution time --
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#f9e2af'  # yellow

  # -- Background jobs --
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70

  # -- Direnv --
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=178

  # -- asdf --
  typeset -g POWERLEVEL9K_ASDF_FOREGROUND=66
  typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND=168
  typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=37
  typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=37
  typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=70
  typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND=37
  typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=134
  typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=38
  typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND=32
  typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND=32
  typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND=67
  typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=125
  typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=129
  typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=31
  typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND=99
  typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=172
  typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND=70

  # -- Shell indicators --
  typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=39
  typeset -g POWERLEVEL9K_RANGER_FOREGROUND=178
  typeset -g POWERLEVEL9K_YAZI_FOREGROUND=178
  typeset -g POWERLEVEL9K_NNN_FOREGROUND=72
  typeset -g POWERLEVEL9K_LF_FOREGROUND=72
  typeset -g POWERLEVEL9K_XPLR_FOREGROUND=72
  typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND=34
  typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND=178
  typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND=74
  typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=33

  # -- System resources --
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=35
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=220
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=160
  typeset -g POWERLEVEL9K_RAM_FOREGROUND=66
  typeset -g POWERLEVEL9K_SWAP_FOREGROUND=96
  typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=66
  typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=178
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=166

  # -- Task managers --
  typeset -g POWERLEVEL9K_TODO_FOREGROUND=110
  typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=110
  typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=74

  # -- Per-directory history --
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=135
  typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=130

  # -- CPU arch --
  typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=172

  # -- Context (user@host) --
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=178
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=180
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=180

  # -- Language version managers --
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=37
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=37
  typeset -g POWERLEVEL9K_GOENV_FOREGROUND=37
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=70
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=70
  typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=70
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=37
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=37
  typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=134
  typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=99
  typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=161
  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=32
  typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=117
  typeset -g POWERLEVEL9K_RBENV_FOREGROUND=168
  typeset -g POWERLEVEL9K_RVM_FOREGROUND=168
  typeset -g POWERLEVEL9K_FVM_FOREGROUND=38
  typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=32
  typeset -g POWERLEVEL9K_JENV_FOREGROUND=32
  typeset -g POWERLEVEL9K_PLENV_FOREGROUND=67
  typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND=67
  typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=99
  typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=160
  typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=172

  # -- Cloud / DevOps --
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=134
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=38
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=38
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND='#cba6f7'   # mauve
  typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=70
  typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=32
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=32
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=32

  # -- Network / misc --
  typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=178
  typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=94
  typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=81
  typeset -g POWERLEVEL9K_IP_FOREGROUND=38
  typeset -g POWERLEVEL9K_PROXY_FOREGROUND=68
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=160
  typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=70
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=178
  typeset -g POWERLEVEL9K_WIFI_FOREGROUND=68
  typeset -g POWERLEVEL9K_TIME_FOREGROUND='#94e2d5'   # teal

  # ---- ACCENTS ----
  # Inline git-status colors — local vars inside my_git_formatter() in segments.zsh:
  #   clean      #a6e3a1  (green)   matches VCS_CLEAN_FOREGROUND above
  #   modified   #f9e2af  (yellow)  matches VCS_MODIFIED_FOREGROUND above
  #   untracked  #74c7ec  (sapphire)
  #   conflicted #f38ba8  (red)
  #   stale      #6c7086  (overlay0 grey, all states when loading)

  # ============ Catppuccin Mocha role map ============
  # When switching themes, update these key prompt colors to match:
  #
  #   Prompt role           | Variable                              | Value
  #   ----------------------|---------------------------------------|-------
  #   directory             | POWERLEVEL9K_DIR_FOREGROUND           | #89b4fa (blue)
  #   directory anchor      | POWERLEVEL9K_DIR_ANCHOR_FOREGROUND    | #74c7ec (sapphire)
  #   git clean             | POWERLEVEL9K_VCS_CLEAN_FOREGROUND     | #a6e3a1 (green)
  #   git modified          | POWERLEVEL9K_VCS_MODIFIED_FOREGROUND  | #f9e2af (yellow)
  #   prompt ok (❯)         | POWERLEVEL9K_PROMPT_CHAR_OK_*         | #a6e3a1 (green)
  #   prompt error (❯)      | POWERLEVEL9K_PROMPT_CHAR_ERROR_*      | #f38ba8 (red)
  #   time                  | POWERLEVEL9K_TIME_FOREGROUND          | #94e2d5 (teal)
  #   exec time             | POWERLEVEL9K_COMMAND_EXECUTION_TIME_* | #f9e2af (yellow)
  #   aws profile           | POWERLEVEL9K_AWS_DEFAULT_FOREGROUND   | #cba6f7 (mauve)

  source "$_cfg/symbols.zsh"
  source "$_cfg/segments.zsh"

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Ruler: horizontal line before each prompt. Set to true and set
  # POWERLEVEL9K_PROMPT_ADD_NEWLINE=false for a more compact look.
  typeset -g POWERLEVEL9K_SHOW_RULER=false

  # Filler between left and right prompt on the first line. Change ' ' to '·' or '─'
  # to make alignment visible, and set POWERLEVEL9K_SHOW_RULER=false.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='.'
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Transient prompt: trim down the prompt when accepting a command line.
  #   off       — never trim
  #   always    — always trim
  #   same-dir  — trim unless cwd changed since last command
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode.
  #   off      — disable
  #   quiet    — enable, suppress console-output warnings
  #   verbose  — enable, warn about console output during zsh init
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Disable hot reload for speed. Apply changes with: source ~/.p10k.zsh
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Example user-defined segment. Add 'example' to POWERLEVEL9K_*_PROMPT_ELEMENTS to enable.
  # See `p10k help segment` for documentation.
  function prompt_example() {
    p10k segment -f 208 -i '⭐' -t 'hello, %n'
  }
  function instant_prompt_example() {
    prompt_example
  }

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'

(( ! ${+functions[p10k]} )) || p10k finalize
