# Generated by Powerlevel10k configuration wizard on 2026-05-02 at 19:25 CEST.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 37983.
# Wizard options: nerdfont-v3 + powerline, small icons, unicode, lean, 12h time, 1 line,
# sparse, many icons, concise, transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.
#
# ──────────────────────────────────────────────────────────────────────────────
# Modular p10k configuration. Edit individual modules instead of this file:
#
#   colors.zsh   — all FOREGROUND / BACKGROUND color values
#   symbols.zsh  — Nerd Font icons, separators, and glyphs
#   segments.zsh — prompt element lists and per-segment behavior
#
# After any change:  source ~/.p10k.zsh
# To reconfigure:    p10k configure  (overwrites this file)
# ──────────────────────────────────────────────────────────────────────────────

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Resolve this file's real path so source works through the ~/.p10k.zsh symlink.
  local _cfg="${${(%):-%x}:A:h}"
  source "$_cfg/colors.zsh"
  source "$_cfg/symbols.zsh"
  source "$_cfg/segments.zsh"

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Ruler: horizontal line before each prompt. Set to true and set
  # POWERLEVEL9K_PROMPT_ADD_NEWLINE=false for a more compact look.
  typeset -g POWERLEVEL9K_SHOW_RULER=false

  # Filler between left and right prompt on the first line. Change ' ' to '·' or '─'
  # to make alignment visible, and set POWERLEVEL9K_SHOW_RULER=false.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Transient prompt: trim down the prompt when accepting a command line.
  #   off       — never trim
  #   always    — always trim
  #   same-dir  — trim unless cwd changed since last command
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode.
  #   off      — disable
  #   quiet    — enable, suppress console-output warnings
  #   verbose  — enable, warn about console output during zsh init
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Disable hot reload for speed. Apply changes with: source ~/.p10k.zsh
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Example user-defined segment. Add 'example' to POWERLEVEL9K_*_PROMPT_ELEMENTS to enable.
  # See `p10k help segment` for documentation.
  function prompt_example() {
    p10k segment -f 208 -i '⭐' -t 'hello, %n'
  }
  function instant_prompt_example() {
    prompt_example
  }

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'

(( ! ${+functions[p10k]} )) || p10k finalize
